@startuml

title Clean architecture example

interface CapitalizeLettersInputPort {
    +capitalizeLetters()
}

interface CapitalizeLettersOutputPort {
    +display()
}

interface InputReader {
    +String getInput()
}

interface OutputDisplayer {
    +void display(String)
}

class CapitalizeLettersUseCase {
    +void capitalizeLetters(String)
}

class CapitalizeLettersController {
    +void capitalizeLetters()
}

class ConsolePrinterPresenter {
    +void display(String)
}

class ScannerInputReader {
    +String getInput()
}

class ConsoleOutputDisplayer {
    +void display(String)
}

class Main{

}
note left: Entry point

CapitalizeLettersInputPort <|.. CapitalizeLettersUseCase
CapitalizeLettersOutputPort <-- CapitalizeLettersUseCase
CapitalizeLettersInputPort <-- CapitalizeLettersController
InputReader <-- CapitalizeLettersController
CapitalizeLettersOutputPort <|.. ConsolePrinterPresenter
OutputDisplayer <-- ConsolePrinterPresenter
InputReader <|.. ScannerInputReader
OutputDisplayer <|.. ConsoleOutputDisplayer
CapitalizeLettersController <-- Main

@enduml
